/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompanyIndexRouteImport } from './routes/company/index'
import { Route as ScoutIndexRouteImport } from './routes/scout/index'
import { Route as ScoutSubmissionsRouteImport } from './routes/scout/submissions'
import { Route as ScoutsPubkeyRouteImport } from './routes/scouts.$pubkey'
import { Route as CompanyRolesRoleIdRouteImport } from './routes/company/roles.$roleId'
import { Route as CompanyRolesNewRouteImport } from './routes/company/roles.new'
import { Route as ScoutTasksRoleIdRouteImport } from './routes/scout/tasks.$roleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyIndexRoute = CompanyIndexRouteImport.update({
  id: '/company/',
  path: '/company/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutIndexRoute = ScoutIndexRouteImport.update({
  id: '/scout/',
  path: '/scout/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutSubmissionsRoute = ScoutSubmissionsRouteImport.update({
  id: '/scout/submissions',
  path: '/scout/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutsPubkeyRoute = ScoutsPubkeyRouteImport.update({
  id: '/scouts/$pubkey',
  path: '/scouts/$pubkey',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRolesRoleIdRoute = CompanyRolesRoleIdRouteImport.update({
  id: '/company/roles/$roleId',
  path: '/company/roles/$roleId',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRolesNewRoute = CompanyRolesNewRouteImport.update({
  id: '/company/roles/new',
  path: '/company/roles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutTasksRoleIdRoute = ScoutTasksRoleIdRouteImport.update({
  id: '/scout/tasks/$roleId',
  path: '/scout/tasks/$roleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/scout/submissions': typeof ScoutSubmissionsRoute
  '/scouts/$pubkey': typeof ScoutsPubkeyRoute
  '/company/': typeof CompanyIndexRoute
  '/scout/': typeof ScoutIndexRoute
  '/company/roles/$roleId': typeof CompanyRolesRoleIdRoute
  '/company/roles/new': typeof CompanyRolesNewRoute
  '/scout/tasks/$roleId': typeof ScoutTasksRoleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/scout/submissions': typeof ScoutSubmissionsRoute
  '/scouts/$pubkey': typeof ScoutsPubkeyRoute
  '/company': typeof CompanyIndexRoute
  '/scout': typeof ScoutIndexRoute
  '/company/roles/$roleId': typeof CompanyRolesRoleIdRoute
  '/company/roles/new': typeof CompanyRolesNewRoute
  '/scout/tasks/$roleId': typeof ScoutTasksRoleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/scout/submissions': typeof ScoutSubmissionsRoute
  '/scouts/$pubkey': typeof ScoutsPubkeyRoute
  '/company/': typeof CompanyIndexRoute
  '/scout/': typeof ScoutIndexRoute
  '/company/roles/$roleId': typeof CompanyRolesRoleIdRoute
  '/company/roles/new': typeof CompanyRolesNewRoute
  '/scout/tasks/$roleId': typeof ScoutTasksRoleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/scout/submissions'
    | '/scouts/$pubkey'
    | '/company/'
    | '/scout/'
    | '/company/roles/$roleId'
    | '/company/roles/new'
    | '/scout/tasks/$roleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/scout/submissions'
    | '/scouts/$pubkey'
    | '/company'
    | '/scout'
    | '/company/roles/$roleId'
    | '/company/roles/new'
    | '/scout/tasks/$roleId'
  id:
    | '__root__'
    | '/'
    | '/scout/submissions'
    | '/scouts/$pubkey'
    | '/company/'
    | '/scout/'
    | '/company/roles/$roleId'
    | '/company/roles/new'
    | '/scout/tasks/$roleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ScoutSubmissionsRoute: typeof ScoutSubmissionsRoute
  ScoutsPubkeyRoute: typeof ScoutsPubkeyRoute
  CompanyIndexRoute: typeof CompanyIndexRoute
  ScoutIndexRoute: typeof ScoutIndexRoute
  CompanyRolesRoleIdRoute: typeof CompanyRolesRoleIdRoute
  CompanyRolesNewRoute: typeof CompanyRolesNewRoute
  ScoutTasksRoleIdRoute: typeof ScoutTasksRoleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/': {
      id: '/company/'
      path: '/company'
      fullPath: '/company/'
      preLoaderRoute: typeof CompanyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scout/': {
      id: '/scout/'
      path: '/scout'
      fullPath: '/scout/'
      preLoaderRoute: typeof ScoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scout/submissions': {
      id: '/scout/submissions'
      path: '/scout/submissions'
      fullPath: '/scout/submissions'
      preLoaderRoute: typeof ScoutSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scouts/$pubkey': {
      id: '/scouts/$pubkey'
      path: '/scouts/$pubkey'
      fullPath: '/scouts/$pubkey'
      preLoaderRoute: typeof ScoutsPubkeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/roles/$roleId': {
      id: '/company/roles/$roleId'
      path: '/company/roles/$roleId'
      fullPath: '/company/roles/$roleId'
      preLoaderRoute: typeof CompanyRolesRoleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/roles/new': {
      id: '/company/roles/new'
      path: '/company/roles/new'
      fullPath: '/company/roles/new'
      preLoaderRoute: typeof CompanyRolesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scout/tasks/$roleId': {
      id: '/scout/tasks/$roleId'
      path: '/scout/tasks/$roleId'
      fullPath: '/scout/tasks/$roleId'
      preLoaderRoute: typeof ScoutTasksRoleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ScoutSubmissionsRoute: ScoutSubmissionsRoute,
  ScoutsPubkeyRoute: ScoutsPubkeyRoute,
  CompanyIndexRoute: CompanyIndexRoute,
  ScoutIndexRoute: ScoutIndexRoute,
  CompanyRolesRoleIdRoute: CompanyRolesRoleIdRoute,
  CompanyRolesNewRoute: CompanyRolesNewRoute,
  ScoutTasksRoleIdRoute: ScoutTasksRoleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
