/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CTokenRouteImport } from './routes/c.$token'
import { Route as CompanyIndexRouteImport } from './routes/company/index'
import { Route as RSlugRouteImport } from './routes/r.$slug'
import { Route as ScoutIndexRouteImport } from './routes/scout/index'
import { Route as ScoutSubmissionsRouteImport } from './routes/scout/submissions'
import { Route as CompanyRolesRoleIdRouteImport } from './routes/company/roles.$roleId'
import { Route as CompanyRolesNewRouteImport } from './routes/company/roles.new'
import { Route as ScoutGigsGigIdRouteImport } from './routes/scout/gigs.$gigId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CTokenRoute = CTokenRouteImport.update({
  id: '/c/$token',
  path: '/c/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyIndexRoute = CompanyIndexRouteImport.update({
  id: '/company/',
  path: '/company/',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutIndexRoute = ScoutIndexRouteImport.update({
  id: '/scout/',
  path: '/scout/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutSubmissionsRoute = ScoutSubmissionsRouteImport.update({
  id: '/scout/submissions',
  path: '/scout/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRolesRoleIdRoute = CompanyRolesRoleIdRouteImport.update({
  id: '/company/roles/$roleId',
  path: '/company/roles/$roleId',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRolesNewRoute = CompanyRolesNewRouteImport.update({
  id: '/company/roles/new',
  path: '/company/roles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutGigsGigIdRoute = ScoutGigsGigIdRouteImport.update({
  id: '/scout/gigs/$gigId',
  path: '/scout/gigs/$gigId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/c/$token': typeof CTokenRoute
  '/r/$slug': typeof RSlugRoute
  '/scout/submissions': typeof ScoutSubmissionsRoute
  '/company/': typeof CompanyIndexRoute
  '/scout/': typeof ScoutIndexRoute
  '/company/roles/$roleId': typeof CompanyRolesRoleIdRoute
  '/company/roles/new': typeof CompanyRolesNewRoute
  '/scout/gigs/$gigId': typeof ScoutGigsGigIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/c/$token': typeof CTokenRoute
  '/r/$slug': typeof RSlugRoute
  '/scout/submissions': typeof ScoutSubmissionsRoute
  '/company': typeof CompanyIndexRoute
  '/scout': typeof ScoutIndexRoute
  '/company/roles/$roleId': typeof CompanyRolesRoleIdRoute
  '/company/roles/new': typeof CompanyRolesNewRoute
  '/scout/gigs/$gigId': typeof ScoutGigsGigIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/c/$token': typeof CTokenRoute
  '/r/$slug': typeof RSlugRoute
  '/scout/submissions': typeof ScoutSubmissionsRoute
  '/company/': typeof CompanyIndexRoute
  '/scout/': typeof ScoutIndexRoute
  '/company/roles/$roleId': typeof CompanyRolesRoleIdRoute
  '/company/roles/new': typeof CompanyRolesNewRoute
  '/scout/gigs/$gigId': typeof ScoutGigsGigIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/c/$token'
    | '/r/$slug'
    | '/scout/submissions'
    | '/company/'
    | '/scout/'
    | '/company/roles/$roleId'
    | '/company/roles/new'
    | '/scout/gigs/$gigId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/c/$token'
    | '/r/$slug'
    | '/scout/submissions'
    | '/company'
    | '/scout'
    | '/company/roles/$roleId'
    | '/company/roles/new'
    | '/scout/gigs/$gigId'
  id:
    | '__root__'
    | '/'
    | '/c/$token'
    | '/r/$slug'
    | '/scout/submissions'
    | '/company/'
    | '/scout/'
    | '/company/roles/$roleId'
    | '/company/roles/new'
    | '/scout/gigs/$gigId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CTokenRoute: typeof CTokenRoute
  RSlugRoute: typeof RSlugRoute
  ScoutSubmissionsRoute: typeof ScoutSubmissionsRoute
  CompanyIndexRoute: typeof CompanyIndexRoute
  ScoutIndexRoute: typeof ScoutIndexRoute
  CompanyRolesRoleIdRoute: typeof CompanyRolesRoleIdRoute
  CompanyRolesNewRoute: typeof CompanyRolesNewRoute
  ScoutGigsGigIdRoute: typeof ScoutGigsGigIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$token': {
      id: '/c/$token'
      path: '/c/$token'
      fullPath: '/c/$token'
      preLoaderRoute: typeof CTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/': {
      id: '/company/'
      path: '/company'
      fullPath: '/company/'
      preLoaderRoute: typeof CompanyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scout/': {
      id: '/scout/'
      path: '/scout'
      fullPath: '/scout/'
      preLoaderRoute: typeof ScoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scout/submissions': {
      id: '/scout/submissions'
      path: '/scout/submissions'
      fullPath: '/scout/submissions'
      preLoaderRoute: typeof ScoutSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/roles/$roleId': {
      id: '/company/roles/$roleId'
      path: '/company/roles/$roleId'
      fullPath: '/company/roles/$roleId'
      preLoaderRoute: typeof CompanyRolesRoleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/roles/new': {
      id: '/company/roles/new'
      path: '/company/roles/new'
      fullPath: '/company/roles/new'
      preLoaderRoute: typeof CompanyRolesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scout/gigs/$gigId': {
      id: '/scout/gigs/$gigId'
      path: '/scout/gigs/$gigId'
      fullPath: '/scout/gigs/$gigId'
      preLoaderRoute: typeof ScoutGigsGigIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CTokenRoute: CTokenRoute,
  RSlugRoute: RSlugRoute,
  ScoutSubmissionsRoute: ScoutSubmissionsRoute,
  CompanyIndexRoute: CompanyIndexRoute,
  ScoutIndexRoute: ScoutIndexRoute,
  CompanyRolesRoleIdRoute: CompanyRolesRoleIdRoute,
  CompanyRolesNewRoute: CompanyRolesNewRoute,
  ScoutGigsGigIdRoute: ScoutGigsGigIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
